name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install cargo-about
      run: cargo install --locked cargo-about
    - name: generate with cargo-about
      run: cargo-about generate about.hbs | sed "s/&quot;/'/g;s/&lt;/</g;s/&gt;/>/g;s/&#x27;/'/g" > thirdparty/THIRDPARTYnew
    - name: test if nothing new
      if: ${{ hashFiles("thirdparty/THIRDPARTYnew") == hashFiles("thirdparty/THIRDPARTY") }}
      run: exit 1
    - name: rename file
      run: mv thirdparty/THIRDPARTYnew thirdparty/THIRDPARTY
    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: false
        message: 'GitHub actions: Cargo-about ${date}'
    
